### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by nowwireless-andy** [takeshixx/webfixy#1]
This program could be very useful to me, but I can't get it to work. I've installed the dependencies and the software runs, but on the first request to the web proxy I get:

```
$ python3 webfixy.py --port <port> --target <target>
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/lib/python3/dist-packages/aiohttp/web.py", line 87, in handle_request
    resp = yield from handler(request)
  File "/home/andy/src/webfixy/libfixy/proxy.py", line 143, in forward_request
    yield from client.close()
TypeError: 'NoneType' object is not iterable
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/lib/python3/dist-packages/aiohttp/web.py", line 87, in handle_request
    resp = yield from handler(request)
  File "/home/andy/src/webfixy/libfixy/proxy.py", line 143, in forward_request
    yield from client.close()
TypeError: 'NoneType' object is not iterable
```

Any ideas for what to try?

**Comment by nowwireless-andy** [comment]
Apologies, I realized that I had Ubuntu package versions of the dependencies installed and not the latest ones from pip. I have updates these now and the software runs, and I am able to load the login screen. However, after logging in, it just gets stuck on the "loading" page. Any suggestions for what to check?

**Comment by takeshixx** [comment]
Thanks for reporting this issue. What version of Python and RouterOS are you running?

**Comment by nowwireless-andy** [comment]
I've tried it on two different machines, one Ubuntu 14.04 (python 3.4.3) and one Ubuntu 16.04 (python 3.5.2).

I've tried it against a variety of different RouterOS versions that I had access to, including 5.21, 5.24, 5.26, 6.4, 6.29, 6.32.4, and with units that have passwords and units that do not. I am at least now getting engine.js back in the browser (and I can load it with curl no problem), but Chrome is rejecting it with:

```
GET http://localhost:8080/webfig/engine.js net::ERR_CONTENT_DECODING_FAILED
```

I tried Firefox as well and it said something about the content encoding not being specified.

I've noticed that when the login screen loads, if I put the incorrect password in, I get "incorrect password", and "internal error" if I put the correct password, but only on RouterOS v5. On v6, I always get "internal error", even with the correct password.

I don't want to inundate you with unwanted debugging output, but please do let me know what specific tests you would like me to run to track down the problem.

**Comment by takeshixx** [comment]
It seems like it fails to properly remove the HTTP content-encoding header which is most likely set to gzip. However, the proxy will gunzip the responses already. This should be fixed with 5d477b05eb863035b7ea50c2c6062005bdc3b685.

If the proxy just silently fails try to start it with the `-v` flag to get more output. Let me know if there are any other issues.
